import localFont from 'next/font/local'

const xcicero = localFont({
  src: '../../public/static/fonts/XCicero_Jakob/Jakob-Semi-Condensed.woff2',
  variable: '--font-xcicero',
})

const aujournuit = localFont({
  src: '../../public/static/fonts/Aujournuit/Aujournuit-Regular.woff2',
  variable: '--font-aujournuit',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      style={{ backgroundColor: 'white' }}
      className={`${xcicero.variable} ${aujournuit.variable}`}
    >
      <body style={{ padding: 0, margin: 0, overflowY: 'scroll' }}>{children}</body>
    </html>
  )
}
